#ifndef GLOBALSETTINGS_HPP
#define GLOBALSETTINGS_HPP

#define LIGNES_FENETRE 20
#define COLONNES_FENETRE 20
#define LIGNES 15
#define COLONNES 20
#define TAILLE_CASE 32
#define LEVEL 1
#define AFFICHER_CORPS 1

#endif //GLOBALSETTINGS_HPP
