//
// Created by Maný on 5/1/2024.
//

#ifndef SNAKE_GLOBAL_SETTINGS_HPP
#define SNAKE_GLOBAL_SETTINGS_HPP

#define LIGNES_FENETRE 20
#define COLONNES_FENETRE 20
#define LIGNES 15
#define COLONNES 20
#define TAILLE_CASE 32
#define LEVEL 0
#define AFFICHER_CORPS 1

#endif //SNAKE_GLOBAL_SETTINGS_HPP
